import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const LOCALCODE_EXPERIMENTAL = truthy("LOCALCODE_EXPERIMENTAL")
const LOCALCODE_DISABLE_CLAUDE_CODE = truthy("LOCALCODE_DISABLE_CLAUDE_CODE")
const LOCALCODE_DISABLE_CLAUDE_CODE_SKILLS =
  LOCALCODE_DISABLE_CLAUDE_CODE || truthy("LOCALCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["LOCALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  LOCALCODE_AUTO_SHARE: truthy("LOCALCODE_AUTO_SHARE"),
  LOCALCODE_AUTO_HEAP_SNAPSHOT: truthy("LOCALCODE_AUTO_HEAP_SNAPSHOT"),
  LOCALCODE_GIT_BASH_PATH: process.env["LOCALCODE_GIT_BASH_PATH"],
  LOCALCODE_CONFIG: process.env["LOCALCODE_CONFIG"],
  LOCALCODE_CONFIG_CONTENT: process.env["LOCALCODE_CONFIG_CONTENT"],
  LOCALCODE_DISABLE_AUTOUPDATE: truthy("LOCALCODE_DISABLE_AUTOUPDATE"),
  LOCALCODE_ALWAYS_NOTIFY_UPDATE: truthy("LOCALCODE_ALWAYS_NOTIFY_UPDATE"),
  LOCALCODE_DISABLE_PRUNE: truthy("LOCALCODE_DISABLE_PRUNE"),
  LOCALCODE_DISABLE_TERMINAL_TITLE: truthy("LOCALCODE_DISABLE_TERMINAL_TITLE"),
  LOCALCODE_SHOW_TTFD: truthy("LOCALCODE_SHOW_TTFD"),
  LOCALCODE_PERMISSION: process.env["LOCALCODE_PERMISSION"],
  LOCALCODE_DISABLE_DEFAULT_PLUGINS: truthy("LOCALCODE_DISABLE_DEFAULT_PLUGINS"),
  LOCALCODE_DISABLE_LSP_DOWNLOAD: truthy("LOCALCODE_DISABLE_LSP_DOWNLOAD"),
  LOCALCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("LOCALCODE_ENABLE_EXPERIMENTAL_MODELS"),
  LOCALCODE_DISABLE_AUTOCOMPACT: truthy("LOCALCODE_DISABLE_AUTOCOMPACT"),
  LOCALCODE_DISABLE_MODELS_FETCH: truthy("LOCALCODE_DISABLE_MODELS_FETCH"),
  LOCALCODE_DISABLE_MOUSE: truthy("LOCALCODE_DISABLE_MOUSE"),
  LOCALCODE_DISABLE_CLAUDE_CODE,
  LOCALCODE_DISABLE_CLAUDE_CODE_PROMPT: LOCALCODE_DISABLE_CLAUDE_CODE || truthy("LOCALCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  LOCALCODE_DISABLE_CLAUDE_CODE_SKILLS,
  LOCALCODE_DISABLE_EXTERNAL_SKILLS: LOCALCODE_DISABLE_CLAUDE_CODE_SKILLS || truthy("LOCALCODE_DISABLE_EXTERNAL_SKILLS"),
  LOCALCODE_FAKE_VCS: process.env["LOCALCODE_FAKE_VCS"],
  LOCALCODE_SERVER_PASSWORD: process.env["LOCALCODE_SERVER_PASSWORD"],
  LOCALCODE_SERVER_USERNAME: process.env["LOCALCODE_SERVER_USERNAME"],
  LOCALCODE_ENABLE_QUESTION_TOOL: truthy("LOCALCODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  LOCALCODE_EXPERIMENTAL,
  LOCALCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("LOCALCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOCALCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("LOCALCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOCALCODE_EXPERIMENTAL_ICON_DISCOVERY: LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  LOCALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("LOCALCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  LOCALCODE_ENABLE_EXA: truthy("LOCALCODE_ENABLE_EXA") || LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_EXA"),
  LOCALCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("LOCALCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  LOCALCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("LOCALCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  LOCALCODE_EXPERIMENTAL_OXFMT: LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_OXFMT"),
  LOCALCODE_EXPERIMENTAL_LSP_TY: truthy("LOCALCODE_EXPERIMENTAL_LSP_TY"),
  LOCALCODE_EXPERIMENTAL_LSP_TOOL: LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_LSP_TOOL"),
  LOCALCODE_EXPERIMENTAL_PLAN_MODE: LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_PLAN_MODE"),
  LOCALCODE_EXPERIMENTAL_MARKDOWN: !falsy("LOCALCODE_EXPERIMENTAL_MARKDOWN"),
  LOCALCODE_MODELS_URL: process.env["LOCALCODE_MODELS_URL"],
  LOCALCODE_MODELS_PATH: process.env["LOCALCODE_MODELS_PATH"],
  LOCALCODE_DISABLE_EMBEDDED_WEB_UI: truthy("LOCALCODE_DISABLE_EMBEDDED_WEB_UI"),
  LOCALCODE_DB: process.env["LOCALCODE_DB"],
  LOCALCODE_DISABLE_CHANNEL_DB: truthy("LOCALCODE_DISABLE_CHANNEL_DB"),
  LOCALCODE_SKIP_MIGRATIONS: truthy("LOCALCODE_SKIP_MIGRATIONS"),
  LOCALCODE_STRICT_CONFIG_DEPS: truthy("LOCALCODE_STRICT_CONFIG_DEPS"),

  LOCALCODE_WORKSPACE_ID: process.env["LOCALCODE_WORKSPACE_ID"],
  LOCALCODE_EXPERIMENTAL_HTTPAPI: truthy("LOCALCODE_EXPERIMENTAL_HTTPAPI"),
  LOCALCODE_EXPERIMENTAL_WORKSPACES: LOCALCODE_EXPERIMENTAL || truthy("LOCALCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get LOCALCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("LOCALCODE_DISABLE_PROJECT_CONFIG")
  },
  get LOCALCODE_TUI_CONFIG() {
    return process.env["LOCALCODE_TUI_CONFIG"]
  },
  get LOCALCODE_CONFIG_DIR() {
    return process.env["LOCALCODE_CONFIG_DIR"]
  },
  get LOCALCODE_PURE() {
    return truthy("LOCALCODE_PURE")
  },
  get LOCALCODE_PLUGIN_META_FILE() {
    return process.env["LOCALCODE_PLUGIN_META_FILE"]
  },
  get LOCALCODE_CLIENT() {
    return process.env["LOCALCODE_CLIENT"] ?? "cli"
  },
}
